markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - autolink
    - xhtml
    - smart
baseurl: "/feed-ticker"
permalink: "/:year/:month/:day/:title/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: browser
  -
    scope:
      path: ""
      type: "posts"
    values:
      css: ['post']
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:path/:basename/
  -
    scope:
      path: "style"
    values:
      permalink: /:path/:basename:output_ext

current_release_download: "https://github.com/maul-esel/feed-ticker/releases/tag/v0.0.1-alpha.1"
