markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - autolink
    - xhtml
    - smart
baseurl: "/feed-ticker"
permalink: "/:year/:month/:day/:title/"
gems:
  - jekyll-feed

name: "FeedTicker Website"
description: "Website for the \"FeedTicker\" Firefox addon, which displays Atom and RSS feeds as a moving ticker in a browser toolbar"
url: "https://maul-esel.github.io"
author: "Dominik Klumpp"
feed:
  path: atom.xml

defaults:
  -
    scope:
      path: ""
    values:
      layout: browser
  -
    scope:
      path: ""
      type: "posts"
    values:
      css: ['post']
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:path/:basename/
  -
    scope:
      path: "style"
    values:
      permalink: /:path/:basename:output_ext

current_release_download: "https://github.com/maul-esel/feed-ticker/tag/v0.0.1-alpha.1"
