markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - autolink
    - xhtml
    - smart
baseurl: "/feed-ticker"
permalink: "/:year/:month/:day/:title/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: browser
  -
    scope:
      path: ""
      type: "posts"
    values:
      css: ['post']
